### ISSUE TITLE
Dose pallene has a plan to support windows platform?

### ISSUE THREAD

**Issue by csbinghu** [pallene-lang/pallene#514] opened 2022-03-29 06:54 UTC
Dose pallene has a plan to support windows platform?

**Comment by hugomg** [comment] 2022-03-29 09:20
Closing this question as a duplicate of issue #322.

Currently we don't have anyone actively working on windows support. However, we woild happily accept pull requests implementing this feature. I expect that the tricky part would be the compilation scripts.

**Closed by hugomg** 2022-03-29 09:20 UTC
